### PR TITLE
Finish ECDH-ES JWE Implementation

### PR DESCRIPTION
**Pull request by techguy613**
Hi rohe,

I've finished the ECDH-ES JWE Implementation for pyjwkest. Please take a look and let me know what you think. Once this is approved and merged, I plan to release a Flask-JWE module for Flask to support  JWE requests and responses that I've already tested with these changes.

Thanks!

### CODE REVIEW

**Comment by rohe** [comment]
Travis CI says it works on Python 2.7 but not on Python 3.4 .
I'll have a look at it tomorrow.

**Comment by techguy613** [comment]
Hey @rohe, I'm going to check 3.4 now and get that fixed.

**Comment by techguy613** [comment]
Looks like the code-quality/landscape check is stuck, however the Travis CI build has passed.

**Comment by rohe** [comment]
That's good enough for me !

**Comment by rohe** [comment]
I guess I should release a new version at pypi now !
Will do tomorrow.

**Comment by techguy613** [comment]
Thanks @rohe!

**Pull request merged**
