### PR TITLE
pass in keys from sign_json to sign_compact

### PR DESCRIPTION
**Pull request by otakup0pe**
This seemed like the easiest way to handle this but perhaps the right choice is to reuse the jws object here https://github.com/rohe/pyjwkest/blob/master/src/jwkest/jws.py#L553 ?

On the surface it seems like this _should_ work without the change as as Line 552 the full `kwargs` is passed in but that was _not_ what I was seeing.

### CODE REVIEW

**Comment by rohe** [comment]
I’ve ported pyjwkest to work on both Python2 and Python3.
In the process I rewrote parts of the code so I don’t know if I can use your pull request as it is.

I plan to push my new code later today or tomorrow.

> 16 apr 2015 kl. 12:38 skrev Jonathan Freedman <notifications@github.com>:
> 
> This seemed like the easiest way to handle this but perhaps the right choice is to reuse the jws object here https://github.com/rohe/pyjwkest/blob/master/src/jwkest/jws.py#L553 ?
> 
> On the surface it seems like this should work without the change as as Line 552 the full kwargs is passed in but that was not what I was seeing.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/rohe/pyjwkest/pull/21
> 
> Commit Summary
> 
> 	• Properly pass in keys to sign_compact from sign_json
> 	• use baked-in b64e and update test for api change
> File Changes
> 
> 	• M .gitignore (1)
> 	• M src/jwkest/jws.py (2)
> 	• M tests/test_1_jws.py (20)
> Patch Links:
> 
> 	• https://github.com/rohe/pyjwkest/pull/21.patch
> 	• https://github.com/rohe/pyjwkest/pull/21.diff
> —
> Reply to this email directly or view it on GitHub.
> 

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by otakup0pe** [comment]
OK I will keep this open and update it once you have pushed your changes.

If you could push your changes to a branch I could also re-make the PR against that.

The choice is yours!

**Comment by rohe** [comment]
pyjwkest is now working on 2.7 and 3.4

> 18 apr 2015 kl. 17:04 skrev Jonathan Freedman <notifications@github.com>:
> 
> OK I will keep this open and update it once you have pushed your changes.
> 
> If you could push your changes to a branch I could also re-make the PR against that.
> 
> The choice is yours!
> 
> —
> Reply to this email directly or view it on GitHub.
> 

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by otakup0pe** [comment]
Updated and seems fine with your Python 3 changes.

**Pull request closed without merging**
